FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    portaudio19-dev \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --only main

COPY fetch_data.py transform_data.py fetch_news.py ./

CMD ["sh", "-c", "python fetch_data.py && python transform_data.py && python fetch_news.py"]